import { Language } from "../data/translations";

type LegalSection = {
  heading: string;
  body: string;
  link?: {
    href: string;
    label: string;
  };
};

type LegalDocument = {
  title: string;
  summary: string;
  sections: LegalSection[];
  lastUpdatedLabel: string;
  lastUpdated: string;
};

type LegalContentByLanguage = {
  footerLinks: {
    privacy: string;
    disclaimer: string;
    terms: string;
  };
  privacy: LegalDocument;
  disclaimer: LegalDocument;
  terms: LegalDocument;
};

export const legalContent: Record<Language, LegalContentByLanguage> = {
  en: {
    footerLinks: {
      privacy: "Privacy Policy",
      disclaimer: "Disclaimer",
      terms: "Terms of Service"
    },
    privacy: {
      title: "Privacy Policy",
      summary:
        "This policy explains how AIJurisdiction handles personal and case-related data in the platform.",
      sections: [
        {
          heading: "Data We Collect",
          body:
            "We may collect account data, submitted case content, uploaded files, and usage logs needed to operate and secure the service."
        },
        {
          heading: "How We Use Data",
          body:
            "Data is used to provide platform features, improve system quality, detect misuse, and support legal and security obligations."
        },
        {
          heading: "Data Sharing",
          body:
            "We do not sell personal data. Data may be shared with service providers acting on our instructions or when required by law."
        },
        {
          heading: "Retention and Security",
          body:
            "We keep data only as long as needed for service and compliance purposes and apply reasonable technical and organizational safeguards."
        },
        {
          heading: "Your Rights",
          body:
            "Depending on your jurisdiction, you may request access, correction, deletion, or processing restrictions for your personal data."
        }
      ],
      lastUpdatedLabel: "Last Updated",
      lastUpdated: "February 18, 2026"
    },
    disclaimer: {
      title: "Disclaimer",
      summary:
        "AIJurisdiction provides AI-generated legal information for support purposes and not as a substitute for professional legal counsel.",
      sections: [
        {
          heading: "AI-Generated Information",
          body:
            "Outputs are generated by AI models and may contain inaccuracies, omissions, or outdated legal interpretations."
        },
        {
          heading: "No Legal Advice",
          body:
            "Content is informational only and does not constitute legal advice for any specific matter."
        },
        {
          heading: "No Attorney-Client Relationship",
          body:
            "Using this platform does not create an attorney-client relationship between you and AIJurisdiction or its operators."
        },
        {
          heading: "Limitation of Liability",
          body:
            "To the fullest extent permitted by law, AIJurisdiction is not liable for losses or damages arising from reliance on platform outputs."
        },
        {
          heading: "No Warranty",
          body:
            "The service and all generated content are provided on an \"as is\" and \"as available\" basis without warranties."
        },
        {
          heading: "Jurisdictional Applicability",
          body:
            "Legal relevance varies by country and region. Users must confirm local applicability with qualified legal professionals."
        },
        {
          heading: "User Responsibility",
          body:
            "You are solely responsible for decisions, filings, and actions taken based on or influenced by platform content."
        },
        {
          heading: "External Resources",
          body:
            "References to external laws, links, or sources are provided for convenience and may change without notice."
        },
        {
          heading: "Right to Modify",
          body:
            "We may update this disclaimer and platform behavior at any time. Continued use indicates acceptance of updates."
        }
      ],
      lastUpdatedLabel: "Last Updated",
      lastUpdated: "February 18, 2026"
    },
    terms: {
      title: "Terms of Service",
      summary:
        "These terms govern your use of Jurisdigta AI Lawyer services, interfaces, and generated outputs.",
      sections: [
        {
          heading: "Acceptance of Terms",
          body:
            "By accessing or using Jurisdigta AI Lawyer, you agree to these terms and to comply with all applicable laws."
        },
        {
          heading: "Permitted Use",
          body:
            "You may use the service only for lawful purposes. You must not upload content that violates another person's rights, applicable laws, or contractual obligations."
        },
        {
          heading: "Account and Access",
          body:
            "You are responsible for keeping your credentials secure and for all activities performed through your account."
        },
        {
          heading: "Intellectual Property",
          body:
            "The software, branding, and underlying systems of the Jurisdigta AI Lawyer platform are protected by the intellectual property rights of their respective owners."
        },
        {
          heading: "Service Changes",
          body:
            "We may update, suspend, or discontinue features, including when changes are required by legal or security obligations."
        },
        {
          heading: "Personal Data Protection",
          body:
            "When using the service, provide only the data necessary for the relevant purpose and upload only content that you are authorized to provide. For more information about personal data processing, see the Privacy Policy.",
          link: {
            href: "/privacy",
            label: "Privacy Policy"
          }
        },
        {
          heading: "AI-Generated Outputs and Human Oversight",
          body:
            "AI-generated outputs may be inaccurate, incomplete, or outdated. Verify them and ensure appropriate human review, by a qualified lawyer where necessary, before any decision, filing, or other action with legal consequences."
        }
      ],
      lastUpdatedLabel: "Last Updated",
      lastUpdated: "July 15, 2026"
    }
  },
  sk: {
    footerLinks: {
      privacy: "Ochrana súkromia",
      disclaimer: "Upozornenie",
      terms: "Podmienky služby"
    },
    privacy: {
      title: "Ochrana sukromia",
      summary:
        "Tieto pravidla vysvetluju, ako AIJurisdiction spracuva osobne a pripadove udaje v platforme.",
      sections: [
        {
          heading: "Ake udaje zbierame",
          body:
            "Mozeme zbierat udaje o ucte, obsah pripadu, nahrane subory a prevadzkove logy potrebne na bezpecnu prevadzku sluzby."
        },
        {
          heading: "Ako udaje pouzivame",
          body:
            "Udaje pouzivame na poskytovanie funkcii, zlepsovanie kvality systemu, detekciu zneuzitia a plnenie pravnych povinnosti."
        },
        {
          heading: "Zdielanie udajov",
          body:
            "Osobne udaje nepredavame. Udaje mozeme zdielat s poskytovatelmi sluzieb alebo ak to vyzaduje zakon."
        },
        {
          heading: "Uchovavanie a bezpecnost",
          body:
            "Udaje uchovavame len po nevyhnutny cas a pouzivame primerane technicke a organizacne ochrany."
        },
        {
          heading: "Vase prava",
          body:
            "Podla jurisdikcie mozete poziadat o pristup, opravu, vymazanie alebo obmedzenie spracuvania osobnych udajov."
        }
      ],
      lastUpdatedLabel: "Posledna aktualizacia",
      lastUpdated: "18. februar 2026"
    },
    disclaimer: {
      title: "Upozornenie",
      summary:
        "AIJurisdiction poskytuje AI generovane pravne informacie len na podporne ucely, nie ako nahradu pravneho poradenstva.",
      sections: [
        {
          heading: "AI generovane informacie",
          body:
            "Vystupy su generovane AI modelmi a mozu obsahovat nepresnosti, vynechania alebo zastarane pravne vyklady."
        },
        {
          heading: "Nejde o pravne poradenstvo",
          body:
            "Obsah je iba informativny a nepredstavuje pravne poradenstvo pre konkretnu situaciu."
        },
        {
          heading: "Bez vztahu klient pravnik",
          body:
            "Pouzivanie platformy nevytvara vztah klient-pravnik medzi vami a AIJurisdiction alebo jeho prevadzkovatelmi."
        },
        {
          heading: "Obmedzenie zodpovednosti",
          body:
            "V maximalnom rozsahu povolenom zakonmi AIJurisdiction nezodpoveda za skody vzniknute spoliehanim sa na vystupy platformy."
        },
        {
          heading: "Bez zaruky",
          body:
            "Sluzba aj generovany obsah su poskytovane v stave \"ako su\" a \"podla dostupnosti\" bez zaruk."
        },
        {
          heading: "Jurisdikcna platnost",
          body:
            "Pravna relevantnost sa lisi podla krajiny a regionu. Pouzivatel musi platnost overit s kvalifikovanym pravnikom."
        },
        {
          heading: "Zodpovednost pouzivatela",
          body:
            "Za rozhodnutia, podania a kroky vykonane na zaklade obsahu platformy nesiete plnu zodpovednost vy."
        },
        {
          heading: "Externe zdroje",
          body:
            "Odkazy na externe predpisy alebo zdroje su orientacne a mozu sa menit bez predchadzajuceho upozornenia."
        },
        {
          heading: "Pravo na zmenu",
          body:
            "Toto upozornenie aj funkcionalitu platformy mozeme kedykolvek upravit. Dalsie pouzivanie znamena suhlas so zmenami."
        }
      ],
      lastUpdatedLabel: "Posledna aktualizacia",
      lastUpdated: "18. februar 2026"
    },
    terms: {
      title: "Podmienky služby",
      summary:
        "Tieto podmienky upravujú používanie služieb, rozhraní a výstupov platformy Jurisdigta AI právnik.",
      sections: [
        {
          heading: "Prijatie podmienok",
          body:
            "Používaním platformy Jurisdigta AI právnik súhlasíte s týmito podmienkami a zaväzujete sa dodržiavať platné právne predpisy."
        },
        {
          heading: "Povolené použitie",
          body:
            "Službu môžete používať iba zákonným spôsobom. Nesmiete nahrávať obsah, ktorý porušuje práva iných osôb, právne predpisy alebo zmluvné povinnosti."
        },
        {
          heading: "Účet a prístup",
          body:
            "Zodpovedáte za bezpečnosť svojich prihlasovacích údajov a za všetky aktivity vykonané prostredníctvom svojho účtu."
        },
        {
          heading: "Duševné vlastníctvo",
          body:
            "Softvér, značka a podkladové systémy platformy Jurisdigta AI právnik sú chránené právami duševného vlastníctva ich príslušných vlastníkov."
        },
        {
          heading: "Zmeny služby",
          body:
            "Funkcie môžeme upraviť, pozastaviť alebo ukončiť, a to aj v prípade zmien vyžadovaných právnymi alebo bezpečnostnými povinnosťami."
        },
        {
          heading: "Ochrana osobných údajov",
          body:
            "Pri používaní služby poskytujte iba údaje potrebné na daný účel a nahrávajte len obsah, ktorý ste oprávnení poskytnúť. Ďalšie informácie o spracúvaní osobných údajov nájdete na stránke Ochrana súkromia.",
          link: {
            href: "/privacy",
            label: "Ochrana súkromia"
          }
        },
        {
          heading: "Výstupy umelej inteligencie a ľudský dohľad",
          body:
            "Výstupy vytvorené umelou inteligenciou môžu byť nepresné, neúplné alebo neaktuálne. Pred rozhodnutím, podaním alebo iným úkonom s právnymi následkami ich overte a zabezpečte primerané ľudské posúdenie, podľa potreby kvalifikovaným právnikom."
        }
      ],
      lastUpdatedLabel: "Posledná aktualizácia",
      lastUpdated: "15. júla 2026"
    }
  },
  de: {
    footerLinks: {
      privacy: "Datenschutz",
      disclaimer: "Haftungsausschluss",
      terms: "Nutzungsbedingungen"
    },
    privacy: {
      title: "Datenschutz",
      summary:
        "Diese Hinweise erklaren, wie AIJurisdiction personenbezogene und fallbezogene Daten verarbeitet.",
      sections: [
        {
          heading: "Welche Daten wir erfassen",
          body:
            "Wir konnen Kontodaten, Fallinhalte, hochgeladene Dateien und Nutzungsprotokolle erfassen, soweit dies fur den Betrieb erforderlich ist."
        },
        {
          heading: "Wie wir Daten verwenden",
          body:
            "Daten werden genutzt, um Funktionen bereitzustellen, die Systemqualitat zu verbessern, Missbrauch zu erkennen und Pflichten zu erfullen."
        },
        {
          heading: "Weitergabe von Daten",
          body:
            "Wir verkaufen keine personenbezogenen Daten. Eine Weitergabe kann an Dienstleister oder bei gesetzlicher Verpflichtung erfolgen."
        },
        {
          heading: "Speicherung und Sicherheit",
          body:
            "Daten werden nur so lange gespeichert, wie es fur Service und Compliance notwendig ist, mit angemessenen Schutzmassnahmen."
        },
        {
          heading: "Ihre Rechte",
          body:
            "Je nach Rechtsraum konnen Sie Auskunft, Berichtigung, Loschung oder Einschrankung der Verarbeitung verlangen."
        }
      ],
      lastUpdatedLabel: "Letzte Aktualisierung",
      lastUpdated: "18. Februar 2026"
    },
    disclaimer: {
      title: "Haftungsausschluss",
      summary:
        "AIJurisdiction stellt KI-generierte Rechtsinformationen zur Verfugung, jedoch keine individuelle Rechtsberatung.",
      sections: [
        {
          heading: "KI-generierte Inhalte",
          body:
            "Ausgaben werden durch KI-Modelle erzeugt und konnen unvollstandig, ungenau oder veraltet sein."
        },
        {
          heading: "Keine Rechtsberatung",
          body:
            "Alle Inhalte dienen nur der Information und ersetzen keine professionelle Rechtsberatung."
        },
        {
          heading: "Kein Mandatsverhaltnis",
          body:
            "Durch die Nutzung entsteht kein Mandats- oder Anwaltsverhaltnis mit AIJurisdiction oder den Betreibern."
        },
        {
          heading: "Haftungsbegrenzung",
          body:
            "Soweit gesetzlich zulassig, haftet AIJurisdiction nicht fur Schaden durch Vertrauen auf Plattformausgaben."
        },
        {
          heading: "Keine Gewahrleistung",
          body:
            "Der Dienst und alle Inhalte werden ohne Gewahr auf \"as is\"- und \"as available\"-Basis bereitgestellt."
        },
        {
          heading: "Jurisdiktionsbezug",
          body:
            "Die rechtliche Anwendbarkeit variiert je nach Land und Region und muss durch qualifizierte Juristen gepruft werden."
        },
        {
          heading: "Verantwortung der Nutzer",
          body:
            "Sie tragen die alleinige Verantwortung fur Entscheidungen und Handlungen auf Basis der Plattforminhalte."
        },
        {
          heading: "Externe Quellen",
          body:
            "Verweise auf externe Gesetze oder Links dienen nur der Orientierung und konnen sich ohne Mitteilung andern."
        },
        {
          heading: "Recht auf Anderung",
          body:
            "Wir konnen diesen Haftungsausschluss und Plattformfunktionen jederzeit andern. Weitere Nutzung gilt als Zustimmung."
        }
      ],
      lastUpdatedLabel: "Letzte Aktualisierung",
      lastUpdated: "18. Februar 2026"
    },
    terms: {
      title: "Nutzungsbedingungen",
      summary:
        "Diese Bedingungen regeln die Nutzung der Dienste, Benutzeroberflächen und generierten Ausgaben von Jurisdigta AI Anwalt.",
      sections: [
        {
          heading: "Annahme der Bedingungen",
          body:
            "Indem Sie auf Jurisdigta AI Anwalt zugreifen oder die Plattform nutzen, erklären Sie sich mit diesen Bedingungen einverstanden und verpflichten sich, die geltenden Rechtsvorschriften einzuhalten."
        },
        {
          heading: "Zulässige Nutzung",
          body:
            "Sie dürfen den Dienst nur zu rechtmäßigen Zwecken nutzen. Sie dürfen keine Inhalte hochladen, die Rechte Dritter, Rechtsvorschriften oder vertragliche Pflichten verletzen."
        },
        {
          heading: "Konto und Zugriff",
          body:
            "Sie sind für die Sicherheit Ihrer Zugangsdaten und für alle über Ihr Konto ausgeführten Aktivitäten verantwortlich."
        },
        {
          heading: "Geistiges Eigentum",
          body:
            "Software, Marke und zugrunde liegende Systeme der Plattform Jurisdigta AI Anwalt sind durch die Rechte des geistigen Eigentums ihrer jeweiligen Inhaber geschützt."
        },
        {
          heading: "Änderungen am Dienst",
          body:
            "Wir können Funktionen ändern, aussetzen oder einstellen, auch wenn dies aufgrund rechtlicher oder sicherheitsbezogener Verpflichtungen erforderlich ist."
        },
        {
          heading: "Schutz personenbezogener Daten",
          body:
            "Stellen Sie bei der Nutzung des Dienstes nur Daten bereit, die für den jeweiligen Zweck erforderlich sind, und laden Sie nur Inhalte hoch, zu deren Bereitstellung Sie berechtigt sind. Weitere Informationen zur Verarbeitung personenbezogener Daten finden Sie unter Datenschutz.",
          link: {
            href: "/privacy",
            label: "Datenschutz"
          }
        },
        {
          heading: "KI-Ausgaben und menschliche Aufsicht",
          body:
            "KI-generierte Ausgaben können ungenau, unvollständig oder veraltet sein. Prüfen Sie sie und stellen Sie vor Entscheidungen, Einreichungen oder anderen Handlungen mit rechtlichen Folgen eine angemessene menschliche Kontrolle sicher, erforderlichenfalls durch einen qualifizierten Rechtsanwalt."
        }
      ],
      lastUpdatedLabel: "Letzte Aktualisierung",
      lastUpdated: "15. Juli 2026"
    }
  }
};
