import { Language } from "../data/translations";

type LegalSection = {
  heading: string;
  body: string;
};

type LegalDocument = {
  title: string;
  summary: string;
  sections: LegalSection[];
  lastUpdatedLabel: string;
  lastUpdated: string;
};

type LegalContentByLanguage = {
  footerLinks: {
    privacy: string;
    disclaimer: string;
    terms: string;
  };
  privacy: LegalDocument;
  disclaimer: LegalDocument;
  terms: LegalDocument;
};

export const legalContent: Record<Language, LegalContentByLanguage> = {
  en: {
    footerLinks: {
      privacy: "Privacy Policy",
      disclaimer: "Disclaimer",
      terms: "Terms of Service"
    },
    privacy: {
      title: "Privacy Policy",
      summary:
        "This policy explains how AIJurisdiction handles personal and case-related data in the platform.",
      sections: [
        {
          heading: "Data We Collect",
          body:
            "We may collect account data, submitted case content, uploaded files, and usage logs needed to operate and secure the service."
        },
        {
          heading: "How We Use Data",
          body:
            "Data is used to provide platform features, improve system quality, detect misuse, and support legal and security obligations."
        },
        {
          heading: "Data Sharing",
          body:
            "We do not sell personal data. Data may be shared with service providers acting on our instructions or when required by law."
        },
        {
          heading: "Retention and Security",
          body:
            "We keep data only as long as needed for service and compliance purposes and apply reasonable technical and organizational safeguards."
        },
        {
          heading: "Your Rights",
          body:
            "Depending on your jurisdiction, you may request access, correction, deletion, or processing restrictions for your personal data."
        }
      ],
      lastUpdatedLabel: "Last Updated",
      lastUpdated: "February 18, 2026"
    },
    disclaimer: {
      title: "Disclaimer",
      summary:
        "AIJurisdiction provides AI-generated legal information for support purposes and not as a substitute for professional legal counsel.",
      sections: [
        {
          heading: "AI-Generated Information",
          body:
            "Outputs are generated by AI models and may contain inaccuracies, omissions, or outdated legal interpretations."
        },
        {
          heading: "No Legal Advice",
          body:
            "Content is informational only and does not constitute legal advice for any specific matter."
        },
        {
          heading: "No Attorney-Client Relationship",
          body:
            "Using this platform does not create an attorney-client relationship between you and AIJurisdiction or its operators."
        },
        {
          heading: "Limitation of Liability",
          body:
            "To the fullest extent permitted by law, AIJurisdiction is not liable for losses or damages arising from reliance on platform outputs."
        },
        {
          heading: "No Warranty",
          body:
            "The service and all generated content are provided on an \"as is\" and \"as available\" basis without warranties."
        },
        {
          heading: "Jurisdictional Applicability",
          body:
            "Legal relevance varies by country and region. Users must confirm local applicability with qualified legal professionals."
        },
        {
          heading: "User Responsibility",
          body:
            "You are solely responsible for decisions, filings, and actions taken based on or influenced by platform content."
        },
        {
          heading: "External Resources",
          body:
            "References to external laws, links, or sources are provided for convenience and may change without notice."
        },
        {
          heading: "Right to Modify",
          body:
            "We may update this disclaimer and platform behavior at any time. Continued use indicates acceptance of updates."
        }
      ],
      lastUpdatedLabel: "Last Updated",
      lastUpdated: "February 18, 2026"
    },
    terms: {
      title: "Terms of Service",
      summary:
        "These terms govern your use of AIJurisdiction services, interfaces, and generated outputs.",
      sections: [
        {
          heading: "Acceptance of Terms",
          body:
            "By accessing or using AIJurisdiction, you agree to comply with these terms and all applicable laws."
        },
        {
          heading: "Permitted Use",
          body:
            "You may use the service only for lawful purposes and must not submit content that violates rights, laws, or contractual duties."
        },
        {
          heading: "Account and Access",
          body:
            "You are responsible for maintaining account confidentiality and for all activities performed under your credentials."
        },
        {
          heading: "Intellectual Property",
          body:
            "Platform software, branding, and underlying systems remain the property of AIJurisdiction and its licensors."
        },
        {
          heading: "Service Changes",
          body:
            "We may update, suspend, or discontinue features at any time, including changes required by legal or security obligations."
        }
      ],
      lastUpdatedLabel: "Last Updated",
      lastUpdated: "February 18, 2026"
    }
  },
  sk: {
    footerLinks: {
      privacy: "Ochrana sukromia",
      disclaimer: "Upozornenie",
      terms: "Podmienky sluzby"
    },
    privacy: {
      title: "Ochrana sukromia",
      summary:
        "Tieto pravidla vysvetluju, ako AIJurisdiction spracuva osobne a pripadove udaje v platforme.",
      sections: [
        {
          heading: "Ake udaje zbierame",
          body:
            "Mozeme zbierat udaje o ucte, obsah pripadu, nahrane subory a prevadzkove logy potrebne na bezpecnu prevadzku sluzby."
        },
        {
          heading: "Ako udaje pouzivame",
          body:
            "Udaje pouzivame na poskytovanie funkcii, zlepsovanie kvality systemu, detekciu zneuzitia a plnenie pravnych povinnosti."
        },
        {
          heading: "Zdielanie udajov",
          body:
            "Osobne udaje nepredavame. Udaje mozeme zdielat s poskytovatelmi sluzieb alebo ak to vyzaduje zakon."
        },
        {
          heading: "Uchovavanie a bezpecnost",
          body:
            "Udaje uchovavame len po nevyhnutny cas a pouzivame primerane technicke a organizacne ochrany."
        },
        {
          heading: "Vase prava",
          body:
            "Podla jurisdikcie mozete poziadat o pristup, opravu, vymazanie alebo obmedzenie spracuvania osobnych udajov."
        }
      ],
      lastUpdatedLabel: "Posledna aktualizacia",
      lastUpdated: "18. februar 2026"
    },
    disclaimer: {
      title: "Upozornenie",
      summary:
        "AIJurisdiction poskytuje AI generovane pravne informacie len na podporne ucely, nie ako nahradu pravneho poradenstva.",
      sections: [
        {
          heading: "AI generovane informacie",
          body:
            "Vystupy su generovane AI modelmi a mozu obsahovat nepresnosti, vynechania alebo zastarane pravne vyklady."
        },
        {
          heading: "Nejde o pravne poradenstvo",
          body:
            "Obsah je iba informativny a nepredstavuje pravne poradenstvo pre konkretnu situaciu."
        },
        {
          heading: "Bez vztahu klient pravnik",
          body:
            "Pouzivanie platformy nevytvara vztah klient-pravnik medzi vami a AIJurisdiction alebo jeho prevadzkovatelmi."
        },
        {
          heading: "Obmedzenie zodpovednosti",
          body:
            "V maximalnom rozsahu povolenom zakonmi AIJurisdiction nezodpoveda za skody vzniknute spoliehanim sa na vystupy platformy."
        },
        {
          heading: "Bez zaruky",
          body:
            "Sluzba aj generovany obsah su poskytovane v stave \"ako su\" a \"podla dostupnosti\" bez zaruk."
        },
        {
          heading: "Jurisdikcna platnost",
          body:
            "Pravna relevantnost sa lisi podla krajiny a regionu. Pouzivatel musi platnost overit s kvalifikovanym pravnikom."
        },
        {
          heading: "Zodpovednost pouzivatela",
          body:
            "Za rozhodnutia, podania a kroky vykonane na zaklade obsahu platformy nesiete plnu zodpovednost vy."
        },
        {
          heading: "Externe zdroje",
          body:
            "Odkazy na externe predpisy alebo zdroje su orientacne a mozu sa menit bez predchadzajuceho upozornenia."
        },
        {
          heading: "Pravo na zmenu",
          body:
            "Toto upozornenie aj funkcionalitu platformy mozeme kedykolvek upravit. Dalsie pouzivanie znamena suhlas so zmenami."
        }
      ],
      lastUpdatedLabel: "Posledna aktualizacia",
      lastUpdated: "18. februar 2026"
    },
    terms: {
      title: "Podmienky sluzby",
      summary:
        "Tieto podmienky upravuju pouzivanie sluzieb, rozhrani a vystupov AIJurisdiction.",
      sections: [
        {
          heading: "Prijatie podmienok",
          body:
            "Pouzivanim AIJurisdiction suhlasite s tymito podmienkami a s platnymi pravnymi predpismi."
        },
        {
          heading: "Povolene pouzitie",
          body:
            "Sluzbu mozete pouzivat iba zakonny sposobom a nesmiete nahravat obsah, ktory porusuje prava alebo zmluvne povinnosti."
        },
        {
          heading: "Ucet a pristup",
          body:
            "Za bezpecnost prihlasovacich udajov a aktivity vykonane cez vas ucet zodpovedate vy."
        },
        {
          heading: "Dusevne vlastnictvo",
          body:
            "Softver, znacka a podkladove systemy platformy zostavaju majetkom AIJurisdiction a jeho licencnych partnerov."
        },
        {
          heading: "Zmeny sluzby",
          body:
            "Funkcie mozeme upravit, pozastavit alebo ukoncit, vratane zmien vyzadovanych pravnymi alebo bezpecnostnymi povinnostami."
        }
      ],
      lastUpdatedLabel: "Posledna aktualizacia",
      lastUpdated: "18. februar 2026"
    }
  },
  de: {
    footerLinks: {
      privacy: "Datenschutz",
      disclaimer: "Haftungsausschluss",
      terms: "Nutzungsbedingungen"
    },
    privacy: {
      title: "Datenschutz",
      summary:
        "Diese Hinweise erklaren, wie AIJurisdiction personenbezogene und fallbezogene Daten verarbeitet.",
      sections: [
        {
          heading: "Welche Daten wir erfassen",
          body:
            "Wir konnen Kontodaten, Fallinhalte, hochgeladene Dateien und Nutzungsprotokolle erfassen, soweit dies fur den Betrieb erforderlich ist."
        },
        {
          heading: "Wie wir Daten verwenden",
          body:
            "Daten werden genutzt, um Funktionen bereitzustellen, die Systemqualitat zu verbessern, Missbrauch zu erkennen und Pflichten zu erfullen."
        },
        {
          heading: "Weitergabe von Daten",
          body:
            "Wir verkaufen keine personenbezogenen Daten. Eine Weitergabe kann an Dienstleister oder bei gesetzlicher Verpflichtung erfolgen."
        },
        {
          heading: "Speicherung und Sicherheit",
          body:
            "Daten werden nur so lange gespeichert, wie es fur Service und Compliance notwendig ist, mit angemessenen Schutzmassnahmen."
        },
        {
          heading: "Ihre Rechte",
          body:
            "Je nach Rechtsraum konnen Sie Auskunft, Berichtigung, Loschung oder Einschrankung der Verarbeitung verlangen."
        }
      ],
      lastUpdatedLabel: "Letzte Aktualisierung",
      lastUpdated: "18. Februar 2026"
    },
    disclaimer: {
      title: "Haftungsausschluss",
      summary:
        "AIJurisdiction stellt KI-generierte Rechtsinformationen zur Verfugung, jedoch keine individuelle Rechtsberatung.",
      sections: [
        {
          heading: "KI-generierte Inhalte",
          body:
            "Ausgaben werden durch KI-Modelle erzeugt und konnen unvollstandig, ungenau oder veraltet sein."
        },
        {
          heading: "Keine Rechtsberatung",
          body:
            "Alle Inhalte dienen nur der Information und ersetzen keine professionelle Rechtsberatung."
        },
        {
          heading: "Kein Mandatsverhaltnis",
          body:
            "Durch die Nutzung entsteht kein Mandats- oder Anwaltsverhaltnis mit AIJurisdiction oder den Betreibern."
        },
        {
          heading: "Haftungsbegrenzung",
          body:
            "Soweit gesetzlich zulassig, haftet AIJurisdiction nicht fur Schaden durch Vertrauen auf Plattformausgaben."
        },
        {
          heading: "Keine Gewahrleistung",
          body:
            "Der Dienst und alle Inhalte werden ohne Gewahr auf \"as is\"- und \"as available\"-Basis bereitgestellt."
        },
        {
          heading: "Jurisdiktionsbezug",
          body:
            "Die rechtliche Anwendbarkeit variiert je nach Land und Region und muss durch qualifizierte Juristen gepruft werden."
        },
        {
          heading: "Verantwortung der Nutzer",
          body:
            "Sie tragen die alleinige Verantwortung fur Entscheidungen und Handlungen auf Basis der Plattforminhalte."
        },
        {
          heading: "Externe Quellen",
          body:
            "Verweise auf externe Gesetze oder Links dienen nur der Orientierung und konnen sich ohne Mitteilung andern."
        },
        {
          heading: "Recht auf Anderung",
          body:
            "Wir konnen diesen Haftungsausschluss und Plattformfunktionen jederzeit andern. Weitere Nutzung gilt als Zustimmung."
        }
      ],
      lastUpdatedLabel: "Letzte Aktualisierung",
      lastUpdated: "18. Februar 2026"
    },
    terms: {
      title: "Nutzungsbedingungen",
      summary:
        "Diese Bedingungen regeln die Nutzung von AIJurisdiction, einschliesslich Oberflachen und erzeugter Inhalte.",
      sections: [
        {
          heading: "Annahme der Bedingungen",
          body:
            "Mit Zugriff auf AIJurisdiction stimmen Sie diesen Bedingungen sowie den anwendbaren Gesetzen zu."
        },
        {
          heading: "Zulassige Nutzung",
          body:
            "Die Plattform darf nur rechtmassig genutzt werden. Unzulassige oder rechtsverletzende Inhalte sind untersagt."
        },
        {
          heading: "Konto und Zugriff",
          body:
            "Sie sind fur die Vertraulichkeit Ihrer Zugangsdaten und fur alle Kontoaktivitaten verantwortlich."
        },
        {
          heading: "Geistiges Eigentum",
          body:
            "Software, Marke und zugrunde liegende Systeme verbleiben im Eigentum von AIJurisdiction und seinen Lizenzgebern."
        },
        {
          heading: "Anderungen am Dienst",
          body:
            "Wir konnen Funktionen jederzeit anpassen, aussetzen oder einstellen, auch zur Einhaltung rechtlicher oder sicherheitsbezogener Vorgaben."
        }
      ],
      lastUpdatedLabel: "Letzte Aktualisierung",
      lastUpdated: "18. Februar 2026"
    }
  }
};
