apiVersion: 1

contactPoints:
  - orgId: 1
    name: JurisDigta Email
    receivers:
      - uid: jurisdigta-email
        type: email
        disableResolveMessage: false
        settings:
          addresses: ${GRAFANA_ALERT_EMAIL_TO}
          singleEmail: true
          subject: '[JurisDigta] {{ template "default.title" . }}'
