from __future__ import annotations

from app.document_templates.models import DocumentTemplateDefinition, TemplateSourceReference

_MINISTRY_PAGE_URL = "https://www.justice.gov.sk/sluzby/vzory-a-formulare/vzory-pre-fo-a-po/"


def build_ministry_page_document_templates() -> list[DocumentTemplateDefinition]:
    entries = [
        _entry(
            template_key="sk.justice.company.sro_articles",
            category="Spolocenska zmluva s.r.o.",
            title="Spolocenska zmluva s.r.o.",
            template_kind="corporate_articles",
            source_format="WEB",
            description="Priama polozka zo stranky Ministerstva spravodlivosti SR pre spolocensku zmluvu s.r.o.",
            keywords=("spolocenska zmluva", "sro", "zakladanie spolocnosti"),
        ),
        _entry(
            template_key="sk.justice.fees.exemption_fo",
            category="Oslobodenie od sudnych poplatkov",
            title="Oslobodenie od sudnych poplatkov FO",
            template_kind="court_fee_exemption_form",
            source_format="RTF/PDF",
            description="Formular na dokladovanie pomerov fyzickej osoby pri navrhu na priznanie oslobodenia od sudnych poplatkov.",
            keywords=("oslobodenie od sudnych poplatkov", "fyzicka osoba", "sudne poplatky"),
        ),
        _entry(
            template_key="sk.justice.fees.exemption_po",
            category="Oslobodenie od sudnych poplatkov",
            title="Oslobodenie od sudnych poplatkov PO",
            template_kind="court_fee_exemption_form",
            source_format="RTF/PDF",
            description="Formular na dokladovanie pomerov pravnickej osoby pri navrhu na priznanie oslobodenia od sudnych poplatkov.",
            keywords=("oslobodenie od sudnych poplatkov", "pravnicka osoba", "sudne poplatky"),
        ),
        _entry(
            template_key="sk.justice.maintenance.minor_child",
            category="Vyzivne",
            title="Vyzivne pre malolete dieta",
            template_kind="maintenance_petition",
            source_format="RTF/PDF",
            description="Formular pre navrh na urcenie vyzivneho pre malolete dieta.",
            keywords=("vyzivne", "malolete dieta", "urcenie vyzivneho"),
        ),
        _entry(
            template_key="sk.justice.maintenance.increase_decrease",
            category="Vyzivne",
            title="Zvysenie alebo znizenie vyzivneho",
            template_kind="maintenance_petition",
            source_format="RTF/PDF",
            description="Formular pre navrh na zvysenie alebo znizenie uz urceneho vyzivneho pre malolete dieta.",
            keywords=("zvysenie vyzivneho", "znizenie vyzivneho", "malolete dieta"),
        ),
        _entry(
            template_key="sk.justice.maintenance.spouses",
            category="Vyzivne",
            title="Vyzivne medzi manzelmi",
            template_kind="maintenance_petition",
            source_format="RTF/PDF",
            description="Formular pre navrh na urcenie vyzivneho medzi manzelmi.",
            keywords=("vyzivne medzi manzelmi", "manzelia", "urcenie vyzivneho"),
        ),
        _entry(
            template_key="sk.justice.payment_order.single_defendant",
            category="Platobne rozkazy",
            title="Platobny rozkaz jeden zalovany",
            template_kind="payment_order_form",
            source_format="RTF",
            description="Priamy formular pre platobny rozkaz s jednym zalovanym.",
            keywords=("platobny rozkaz", "jeden zalovany", "sudne podanie"),
        ),
        _entry(
            template_key="sk.justice.payment_order.multiple_defendants",
            category="Platobne rozkazy",
            title="Platobny rozkaz viac zalovanych",
            template_kind="payment_order_form",
            source_format="RTF",
            description="Priamy formular pre platobny rozkaz s viacerymi zalovanymi.",
            keywords=("platobny rozkaz", "viac zalovanych", "sudne podanie"),
        ),
        _entry(
            template_key="sk.justice.bill_of_exchange_order.single_defendant",
            category="Platobne rozkazy",
            title="Zmenkovy platobny rozkaz jeden zalovany",
            template_kind="bill_of_exchange_payment_order_form",
            source_format="RTF",
            description="Priamy formular pre zmenkovy platobny rozkaz s jednym zalovanym.",
            keywords=("zmenkovy platobny rozkaz", "jeden zalovany", "zmenka"),
        ),
        _entry(
            template_key="sk.justice.bill_of_exchange_order.multiple_defendants",
            category="Platobne rozkazy",
            title="Zmenkovy platobny rozkaz viac zalovanych",
            template_kind="bill_of_exchange_payment_order_form",
            source_format="RTF",
            description="Priamy formular pre zmenkovy platobny rozkaz s viacerymi zalovanymi.",
            keywords=("zmenkovy platobny rozkaz", "viac zalovanych", "zmenka"),
        ),
        _entry(
            template_key="sk.justice.insolvency.asset_list",
            category="Konkurz a restrukturalizacia",
            title="Zoznam majetku",
            template_kind="insolvency_form",
            source_format="RTF",
            description="Formular pre konkurz a restrukturalizaciu: zoznam majetku.",
            keywords=("konkurz", "restrukturalizacia", "zoznam majetku"),
        ),
        _entry(
            template_key="sk.justice.insolvency.summary_overview",
            category="Konkurz a restrukturalizacia",
            title="Suhrnny prehlad",
            template_kind="insolvency_form",
            source_format="RTF",
            description="Formular pre konkurz a restrukturalizaciu: suhrnny prehlad.",
            keywords=("konkurz", "restrukturalizacia", "suhrnny prehlad"),
        ),
        _entry(
            template_key="sk.justice.insolvency.liability_list",
            category="Konkurz a restrukturalizacia",
            title="Zoznam zavazkov",
            template_kind="insolvency_form",
            source_format="RTF",
            description="Formular pre konkurz a restrukturalizaciu: zoznam zavazkov.",
            keywords=("konkurz", "restrukturalizacia", "zoznam zavazkov"),
        ),
        _entry(
            template_key="sk.justice.insolvency.contract_overview",
            category="Konkurz a restrukturalizacia",
            title="Zmluvne a ine prehlady",
            template_kind="insolvency_form",
            source_format="RTF",
            description="Formular pre konkurz a restrukturalizaciu: zmluvne a ine prehlady.",
            keywords=("konkurz", "restrukturalizacia", "zmluvne prehlady"),
        ),
        _entry(
            template_key="sk.justice.insolvency.claim_priority_objection",
            category="Konkurz a restrukturalizacia",
            title="Namietka poradia pohladavky",
            template_kind="insolvency_form",
            source_format="RTF",
            description="Formular pre namietku poradia pohladavky v konkurznom alebo restrukturalizacnom konani.",
            keywords=("namietka poradia pohladavky", "konkurz", "restrukturalizacia"),
        ),
        _entry(
            template_key="sk.justice.insolvency.claim_denial",
            category="Konkurz a restrukturalizacia",
            title="Popretie pohladavky",
            template_kind="insolvency_form",
            source_format="RTF",
            description="Formular pre popretie pohladavky v konkurznom alebo restrukturalizacnom konani.",
            keywords=("popretie pohladavky", "konkurz", "restrukturalizacia"),
        ),
        _entry(
            template_key="sk.justice.insolvency.free_attachment",
            category="Konkurz a restrukturalizacia",
            title="Volna priloha",
            template_kind="insolvency_form",
            source_format="RTF",
            description="Doplnkova volna priloha pre konkurz a restrukturalizaciu.",
            keywords=("volna priloha", "konkurz", "restrukturalizacia"),
        ),
        _entry(
            template_key="sk.justice.preventive_restructuring.coverage_gap_projection",
            category="Konkurz a restrukturalizacia",
            title="Zjednoduseny formular projekcie mesacneho vyvoja medzery krytia",
            template_kind="preventive_restructuring_form",
            source_format="XLS/PDF",
            description="Priamy formular pre preventivnu restrukturalizaciu: projekcia mesacneho vyvoja medzery krytia.",
            keywords=("preventivna restrukturalizacia", "medzera krytia", "projekcia"),
        ),
        _entry(
            template_key="sk.justice.company_registry.initial_registration",
            category="Obchodny register",
            title="Navrh na zapis udajov do obchodneho registra pre podania v elektronickej podobe",
            template_kind="company_registry_filing",
            source_format="WEBFORM",
            description="Priama polozka pre elektronicky navrh na zapis udajov do obchodneho registra.",
            keywords=("obchodny register", "zapis udajov", "elektronicke podanie"),
        ),
        _entry(
            template_key="sk.justice.company_registry.change_registration",
            category="Obchodny register",
            title="Navrh na zapis zmeny udajov do obchodneho registra pre podania v elektronickej podobe",
            template_kind="company_registry_filing",
            source_format="WEBFORM",
            description="Priama polozka pre elektronicky navrh na zapis zmeny udajov do obchodneho registra.",
            keywords=("obchodny register", "zmena udajov", "elektronicke podanie"),
        ),
        _entry(
            template_key="sk.justice.company_registry.deletion_registration",
            category="Obchodny register",
            title="Navrh na vymaz udajov z obchodneho registra pre podania v elektronickej podobe",
            template_kind="company_registry_filing",
            source_format="WEBFORM",
            description="Priama polozka pre elektronicky navrh na vymaz udajov z obchodneho registra.",
            keywords=("obchodny register", "vymaz udajov", "elektronicke podanie"),
        ),
        _entry(
            template_key="sk.justice.company_registry.legal_form_change",
            category="Obchodny register",
            title="Navrh na zapis zmeny pravnej formy",
            template_kind="company_registry_filing",
            source_format="WEBFORM",
            description="Priama polozka pre zapis zmeny pravnej formy v obchodnom registri.",
            keywords=("obchodny register", "zmena pravnej formy", "elektronicke podanie"),
        ),
        _entry(
            template_key="sk.justice.company_registry.registration_objection",
            category="Obchodny register",
            title="Podanie namietky proti odmietnutiu vykonania zapisu",
            template_kind="company_registry_objection",
            source_format="WEBFORM",
            description="Priama polozka pre podanie namietky proti odmietnutiu vykonania zapisu v obchodnom registri.",
            keywords=("obchodny register", "namietka", "odmietnutie vykonania zapisu"),
        ),
        _entry(
            template_key="sk.justice.company_registry.objection_appeal",
            category="Obchodny register",
            title="Odvolanie proti uzneseniu sudu o zamietnuti namietok",
            template_kind="company_registry_appeal",
            source_format="WEBFORM",
            description="Priama polozka pre odvolanie proti uzneseniu sudu o zamietnuti namietok v obchodnom registri.",
            keywords=("obchodny register", "odvolanie", "zamietnutie namietok"),
        ),
        _entry(
            template_key="sk.justice.company_registry.data_alignment",
            category="Obchodny register",
            title="Navrh na zacatie konania o zosuladeni udajov so skutocnym pravnym stavom",
            template_kind="company_registry_filing",
            source_format="WEBFORM",
            description="Priama polozka pre zacatie konania o zosuladeni udajov v obchodnom registri.",
            keywords=("obchodny register", "zosuladenie udajov", "skutocny pravny stav"),
        ),
        _entry(
            template_key="sk.justice.company_registry.beneficial_owner_change",
            category="Obchodny register",
            title="Navrh na zapis zmeny udajov o konecnom uzivatelovi vyhod v elektronickej podobe",
            template_kind="company_registry_filing",
            source_format="WEBFORM",
            description="Priama polozka pre zapis zmeny udajov o konecnom uzivatelovi vyhod v obchodnom registri.",
            keywords=("konecny uzivatel vyhod", "obchodny register", "zmena udajov"),
        ),
        _entry(
            template_key="sk.justice.judge.annual_statistical_report",
            category="Rocny statisticky vykaz sudcu",
            title="Rocny statisticky vykaz sudcu",
            template_kind="judicial_report_form",
            source_format="RTF",
            description="Vzor rocneho statistickeho vykazu sudcu.",
            keywords=("sudca", "rocny statisticky vykaz", "vykaz"),
        ),
        _entry(
            template_key="sk.justice.enforcement.authorization_request",
            category="Exekutori",
            title="Ziadost o udelenie poverenia",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: ziadost o udelenie poverenia.",
            keywords=("exekucia", "ziadost o udelenie poverenia", "exekutor"),
        ),
        _entry(
            template_key="sk.justice.enforcement.execution_notice",
            category="Exekutori",
            title="Upovedomenie o zacati exekucie",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: upovedomenie o zacati exekucie.",
            keywords=("exekucia", "upovedomenie o zacati exekucie", "exekutor"),
        ),
        _entry(
            template_key="sk.justice.enforcement.salary_deduction_notice",
            category="Exekutori",
            title="Upovedomenie o sposobe vykonania exekucie - zrazky zo mzdy",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: upovedomenie o sposobe vykonania exekucie zrazkami zo mzdy.",
            keywords=("exekucia", "zrazky zo mzdy", "upovedomenie"),
        ),
        _entry(
            template_key="sk.justice.enforcement.other_income_deduction_notice",
            category="Exekutori",
            title="Upovedomenie o sposobe vykonania exekucie - zrazky z inych prijmov",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: upovedomenie o sposobe vykonania exekucie zrazkami z inych prijmov.",
            keywords=("exekucia", "zrazky z inych prijmov", "upovedomenie"),
        ),
        _entry(
            template_key="sk.justice.enforcement.account_notice",
            category="Exekutori",
            title="Upovedomenie o sposobe vykonania exekucie - ucet",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: upovedomenie o sposobe vykonania exekucie prikazom na ucet.",
            keywords=("exekucia", "ucet", "upovedomenie"),
        ),
        _entry(
            template_key="sk.justice.enforcement.salary_deduction_order",
            category="Exekutori",
            title="Prikaz na zacatie exekucie - zrazky zo mzdy",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: prikaz na zacatie exekucie zrazkami zo mzdy.",
            keywords=("exekucia", "prikaz na zacatie exekucie", "zrazky zo mzdy"),
        ),
        _entry(
            template_key="sk.justice.enforcement.other_income_deduction_order",
            category="Exekutori",
            title="Prikaz na zacatie exekucie - zrazky z inych prijmov",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: prikaz na zacatie exekucie zrazkami z inych prijmov.",
            keywords=("exekucia", "prikaz na zacatie exekucie", "zrazky z inych prijmov"),
        ),
        _entry(
            template_key="sk.justice.enforcement.account_order",
            category="Exekutori",
            title="Prikaz na zacatie exekucie - ucet",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: prikaz na zacatie exekucie prikazom na ucet.",
            keywords=("exekucia", "prikaz na zacatie exekucie", "ucet"),
        ),
        _entry(
            template_key="sk.justice.enforcement.account_execution_order",
            category="Exekutori",
            title="Exekucny prikaz - ucet",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: exekucny prikaz na ucet.",
            keywords=("exekucia", "exekucny prikaz", "ucet"),
        ),
        _entry(
            template_key="sk.justice.enforcement.movable_property_inventory",
            category="Exekutori",
            title="Supis hnutelnych veci",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: supis hnutelnych veci.",
            keywords=("exekucia", "supis hnutelnych veci", "hnutelne veci"),
        ),
        _entry(
            template_key="sk.justice.enforcement.inventory_execution_notice",
            category="Exekutori",
            title="Upovedomenie o vykonani supisu - HV",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: upovedomenie o vykonani supisu hnutelnych veci.",
            keywords=("exekucia", "supis", "hnutelne veci"),
        ),
        _entry(
            template_key="sk.justice.enforcement.auction_schedule_notice",
            category="Exekutori",
            title="Oznamenie terminu drazby - HV",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: oznamenie terminu drazby hnutelnych veci.",
            keywords=("exekucia", "drazba", "hnutelne veci"),
        ),
        _entry(
            template_key="sk.justice.enforcement.auction_record_movable",
            category="Exekutori",
            title="Zapisnica o drazbe - HV",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: zapisnica o drazbe hnutelnych veci.",
            keywords=("exekucia", "zapisnica o drazbe", "hnutelne veci"),
        ),
        _entry(
            template_key="sk.justice.enforcement.real_estate_auction_notice",
            category="Exekutori",
            title="Vyhlaska o drazbe nehnutelnosti",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: vyhlaska o drazbe nehnutelnosti.",
            keywords=("exekucia", "drazba nehnutelnosti", "vyhlaska"),
        ),
        _entry(
            template_key="sk.justice.enforcement.hammer_award_record",
            category="Exekutori",
            title="Zapisnica o udeleni priklepu pri drazbe nehn.",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: zapisnica o udeleni priklepu pri drazbe nehnutelnosti.",
            keywords=("exekucia", "priklep", "drazba nehnutelnosti"),
        ),
        _entry(
            template_key="sk.justice.enforcement.hammer_approval_motion",
            category="Exekutori",
            title="Navrh na schvalenie priklepu pri drazbe nehn.",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: navrh na schvalenie priklepu pri drazbe nehnutelnosti.",
            keywords=("exekucia", "schvalenie priklepu", "drazba nehnutelnosti"),
        ),
        _entry(
            template_key="sk.justice.enforcement.proceeds_distribution_record",
            category="Exekutori",
            title="Zapisnica o rozvrhu vytazku drazby nehn.",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: zapisnica o rozvrhu vytazku drazby nehnutelnosti.",
            keywords=("exekucia", "rozvrh vytazku", "drazba nehnutelnosti"),
        ),
        _entry(
            template_key="sk.justice.enforcement.debt_fulfillment_confirmation",
            category="Exekutori",
            title="Potvrdenie o splneni dlhu alebo jeho casti",
            template_kind="enforcement_form",
            source_format="RTF",
            description="Vzory tlaciv pre sudnych exekutorov: potvrdenie o splneni dlhu alebo jeho casti.",
            keywords=("exekucia", "potvrdenie o splneni dlhu", "dlh"),
        ),
        _entry(
            template_key="sk.justice.payment_order.objection_banska_bystrica",
            category="Upominacie konanie",
            title="Upominacie konanie - odpor proti platobnemu rozkazu Okresnemu sudu Banska Bystrica",
            template_kind="payment_order_objection_form",
            source_format="PDF",
            description="Priamy formular pre odpor proti platobnemu rozkazu v upominacom konani.",
            keywords=("upominacie konanie", "odpor proti platobnemu rozkazu", "banska bystrica"),
        ),
        _entry(
            template_key="sk.justice.payment_order.installment_request_banska_bystrica",
            category="Upominacie konanie",
            title="Upominacie konanie - ziadost o povolenie plnenia v splatkach Okresnemu sudu Banska Bystrica",
            template_kind="payment_order_installment_request_form",
            source_format="PDF",
            description="Priamy formular pre ziadost o povolenie plnenia v splatkach v upominacom konani.",
            keywords=("upominacie konanie", "plnenie v splatkach", "banska bystrica"),
        ),
    ]
    return entries


def _entry(
    *,
    template_key: str,
    category: str,
    title: str,
    template_kind: str,
    source_format: str,
    description: str,
    keywords: tuple[str, ...],
) -> DocumentTemplateDefinition:
    return DocumentTemplateDefinition(
        template_id=f"seed-{template_key.replace('.', '-')}",
        template_key=template_key,
        jurisdiction="SK",
        language="sk-SK",
        category=category,
        title=title,
        template_kind=template_kind,
        description=description,
        source_format=source_format,
        source_url=_MINISTRY_PAGE_URL,
        body="",
        keywords=keywords,
        flow_keys=(),
        placeholders=(),
        source_refs=(
            TemplateSourceReference(
                label="Vzory pre fyzicke a pravnicke osoby",
                url=_MINISTRY_PAGE_URL,
                publisher="Ministerstvo spravodlivosti SR",
                source_kind="official_form_index",
                notes="Priama polozka zo stranky k 2026-08-14; bez importu z externych subkatalogov.",
            ),
        ),
        is_enabled=True,
        is_deleted=False,
    )
